### ISSUE TITLE
Flickering 

### ISSUE THREAD

**Issue by Reginold-P** [artginzburg/MiddleClick-Ventura#29]
I installed it using brew and when I started it, it shows the icon on the menu bar.
When I click or tab my three fingers, it not working and I'm seeing the icon flickering on the menubar
I'm on AppleSilicon and running the v2.5

**Comment by dsalavei** [comment]
It's the same for me, running 2.5 on MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports) Intel-based

**Comment by jnooree** [comment]
Same for me (v2.5). v2.4.8.1 works properly.

**Comment by Wiredframe** [comment]
Same for me, went back to the previous non M1 version for now. ☺️

**Comment by sky-andremartins** [comment]
Same

**Comment by sky-andremartins** [comment]
Fixed it on Mac M1 Big Sur 11.6 by:

Remove MiddleClick from Security & Privacy > Privacy > Accessibility
```
killall MiddleClick
brew reinstall --cask --no-quarantine middleclick
```
And then add it again to Security & Privacy > Privacy > Accessibility

**Comment by artginzburg** [comment]
The flickering happens because the app doesn't have Accessibility permission. It's waiting for the user to grant the permission, and restarts every 5 seconds to get to work as soon as the permission is granted.

After next release, the menu bar icon will check for Accessibility permission and appear disabled if it's not granted. The app menu will also have some helpful items related to permission status.

When #46 is fully tested, the menu bar icon will not flicker at all.

**Comment by artginzburg** [comment]
Fixed in the new release.
